from decimal import Decimal
from typing import Optional
from datetime import date, datetime
from sqlalchemy import (
    String, Numeric, Date, DateTime, Text, Integer, ForeignKey, Enum, Index,
    CheckConstraint, func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.models.enums import PaymentDirection
from app.utils.helpers import generate_uuid
from app.db.base import Base


class Payment(Base):
    __tablename__ = "payments"

    # Eagerly fetch server-generated created_at during flush so it's never
    # left "expired" after commit (async + expired attr = MissingGreenlet).
    __mapper_args__ = {"eager_defaults": True}

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=generate_uuid)

    # Null for a walk-in refund - no ongoing balance to adjust, this row
    # is the terminal record of the cash-out event on its own.
    party_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("parties.id"), nullable=True
    )
    direction: Mapped[PaymentDirection] = mapped_column(
        Enum(PaymentDirection, name="payment_direction"), nullable=False
    )
    amount: Mapped[Decimal] = mapped_column(Numeric(12, 2), nullable=False)
    method: Mapped[str] = mapped_column(String(50), nullable=False)
    payment_date: Mapped[date] = mapped_column(Date, nullable=False)
    reference_no: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Set only when this payment is a refund auto-generated by a walk-in
    # sales return - links the cash-out back to the return that caused it.
    sales_return_id: Mapped[Optional[str]] = mapped_column(
        String(36), ForeignKey("sales_returns.id"), nullable=True
    )

    # Optional: the completed sale order this payment is applied to. One
    # payment applies to one sale; several payments can accumulate against
    # the same sale (3000 today, 1200 later, 800 later). This drives the
    # per-order tracking in sale.amount_paid so outstanding is computed
    # order-by-order instead of just against the party's overall balance.
    # Only meaningful for RECEIVED_FROM_CUSTOMER. Null = on-account.
    sale_id: Mapped[Optional[str]] = mapped_column(
        String(36), ForeignKey("sales.id"), nullable=True
    )

    # Mirror of sale_id for the supplier side: the received purchase
    # invoice this payment settles. Drives per-invoice tracking in
    # purchase.amount_paid. Only meaningful for PAID_TO_SUPPLIER.
    purchase_id: Mapped[Optional[str]] = mapped_column(
        String(36), ForeignKey("purchases.id"), nullable=True
    )

    created_by: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("users.id"), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    party: Mapped[Optional["Party"]] = relationship("Party", back_populates="payments")
    sales_return: Mapped[Optional["SalesReturn"]] = relationship("SalesReturn")
    sale: Mapped[Optional["Sale"]] = relationship("Sale")
    purchase: Mapped[Optional["Purchase"]] = relationship("Purchase")

    __table_args__ = (
        Index("idx_payment_party_id", "party_id"),
        Index("idx_payment_date", "payment_date"),
        CheckConstraint("amount > 0", name="check_payment_amount_positive"),
    )

    def __repr__(self):
        return f"<Payment(id={self.id}, direction={self.direction}, amount={self.amount})>"
